### ISSUE TITLE
mercantile tiles method is not idempotent

### ISSUE THREAD

**Issue by walkingpendulum** [mapbox/mercantile#87]
Hi,

I run `tiles` method once and get tiles A, ...; then I get bbox coordinates for A, let it be A_bbox.
Then if I run `tiles` for A_bbox I expect mercantile to return only tile A, but it return A and some other tiles.

Code for reproduction:
```bash
$ python -c "import mercantile as m; print [m.feature(x)['bbox'] for x in list(m.tiles(-122.080078125, 37.5097258429375, -122.0361328125, 37.54457732085582, zooms=13))]"

[[-122.080078125, 37.5097258429375, -122.0361328125, 37.54457732085582], [-122.080078125, 37.474858084971025, -122.0361328125, 37.5097258429375], [-122.0361328125, 37.5097258429375, -121.9921875, 37.54457732085582], [-122.0361328125, 37.474858084971025, -121.9921875, 37.5097258429375]]
```

**Comment by sgillies** [comment]
@walkingpendulum this looks very related to #83, yes? I'm not sure whether using an epsilon value is always right here. I'd love your feedback on that if you will share it.

**Comment by walkingpendulum** [comment]
@sgillies yes it is duplicate for #84, thank you.

I think that epsilon approach is not address the real issue but sweep the issue under the carpet. The real problem is that for fixed zoom level some points are belongs to multiple tiles. 

Personally, I would prefer to throw north side and east side points away from a tile box, so to speak. 

More concretely, [here](https://github.com/mapbox/mercantile/blob/5821d09ca20709e28b49aa2ea069f42acca27bb6/mercantile/__init__.py#L329) lets calculate 
```
ll_of_ur = tile(tile(e, n, z).west, tile(e, n, z).south, z)
```
and do not increase upper bound for `i`/`j` ranges by 1 in L329-330 if `ll_of_ur.west == ll.east`/`ll_of_ur.south == ll.north` respectively. Of course, floats should be compared with some epsilon precision but it is not the same epsilon as in discussion of #84.

**Comment by sgillies** [comment]
@walkingpendulum if our computers could do floating point math perfectly, you'd get 9 tiles back if you asked for all the tiles that intersected or touched the bounding box of one tile, yes? Because points on the boundary of tile A are equally on the boundary of all the surrounding tiles. Getting a single tile back is also right in some sense. Getting 2-8 back is wrong.

Until we sort this out, the workaround is to avoid going back and forth between tile and spatial coordinates.

**Comment by walkingpendulum** [comment]
@sgilles, now I see that current tiles method behaves in consistent way with what you expect it will do.
My initial problem that leads me to this issue was to envelope some area in box consisting of tms/google tiles for fixed zoom level. And then I need to check if some area already was builded in aforementioned way. 
At first I think all I need is to call tile method for area box nodes and check if resulted tiles are belongs to my area, but the very first test case with single tile bounding box proved that I was wrong.

**Comment by jagill** [comment]
If you interpret `intersects` according to the OpenGIS Simple Features Specification, then `tiles(*bounds(tile), zooms=tile.z)` returning 9 tiles is correct.  If you interpret it more akin to `overlaps`, then it should return 1 tile.  Since `shapely` and most geometrical/geographical libraries use SFS, I'd suggest returning 9 tiles, and the docs should be updated accordingly.

Alternatively, you could change the docs to say "Get the tiles overlapping a geographic bounding box".

**Comment by sgillies** [comment]
@jagill after more consideration, "overlaps" is what I'm looking for. I'm making a tiny adjustment to the code and updating the docs for 1.1.2.
