### ISSUE TITLE
QuadKeyError should inherit from ValueError?

### ISSUE THREAD

**Issue by jagill** [mapbox/mercantile#98]
Supplying an invalid quadkey (like "5") to `quadkey_to_tile` raises a QuadKeyError.  The purposes of the built-in ValueError is to specify that the type of the argument is correct, but it's an incorrect value.  This is the case for a quadkey of "5" (ie, a string that is not a valid quadkey).  I think Mercantile did this before.

This has an impact because code that is checking for ValueError will break (as happened for us).  Also, an error which doesn't inherit from ValueError has different semantics; code that is trying to handle incorrect input won't know what to do with QuadKeyError.

**Comment by sgillies** [comment]
@jagill sorry about the surprise change to the API. Raising a ValueError there was a mistake. The intent in mercantile is to raise package-specific errors in order to make the source of bugs more clear: a MercantileError indicates a mercantile usage bug in user code, a builtin error indicates a mercantile bug. I got this idea from Brett Slatkin.

We can make QuadKeyError derive from ValueError also until 2.0, with a deprecation notice. Will that work for you?
